[package]
name = "advent-of-code-2018-day-02"
version = "1.0.0"
authors = ["Joshua Vega <jvega@jsvcycling.com>"]
edition = "2018"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
